### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by muhammadzaheer123** [ConnectyCube/connectycube-reactnative-samples#135]

**Comment by muhammadzaheer123** [comment]
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.connectycube/com.connectycube.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.connectycube.MainActivity" on path: DexPathList[[zip file "/data/app/com.connectycube-2/base.apk"],nativeLibraryDirectories=[/data/app/com.connectycube-2/lib/arm, /data/app/com.connectycube-2/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2868)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3064)
        at android.app.ActivityThread.-wrap14(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1659)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6816)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1563)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1451)

**Comment by ccvlad** [comment]
You have not provided any description other than an error in Java code. The issue doesn't related to the `react-native-connectycube`. Check the class `MainActivity` in Java code.
