### ISSUE TITLE
Create and send message for API rest using python

### ISSUE THREAD

**Issue by AnnBenavides** [ConnectyCube/connectycube-reactnative-samples#25]
Hello again, i have the follow error for trying to [make a message as the documantation](https://developers.connectycube.com/server/chat?id=create-a-message) says:
```python
Traceback (most recent call last):
  File "<path>\venv\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "<path>\venv\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "<path>\hermesbff\endpoints\cc_message.py", line 27, in send_message_to_group
    return await self.post_send_message(usertoken, parameters)
  File "<path>\hermesbff\endpoints\cc_message.py", line 41, in post_send_message
    response = await self.application.http_client.fetch(request)
tornado.httpclient.HTTPClientError: HTTP 404: Not Found
ERROR:tornado.access:500 POST /cc/messages (::1) 16031.01ms
```
My code in tornado python3.6 is:
```python
import json
import tornado.web
from tornado.httpclient import HTTPRequest
from static.connecticube_credentials import API_HOST

class CCMessageHandler(tornado.web.RequestHandler):
    async def send_message_to_chat(self, usertoken, reciever_id, message, data):
        parameters = {
            "recipient_id": reciever_id,
            "message": message,
            "data": data,
            "send_to_chat": "1"
        }
        return await self.post_send_message(usertoken, parameters)

    async def send_message_to_group(self, usertoken, dialog_id, message, data):
        parameters = {
            "chat_dialog_id": dialog_id,
            "message": message,
            "data": data,
            "send_to_chat": "1"
        }
        return await self.post_send_message(usertoken, parameters)

    async def post_send_message(self, usertoken, parameters): 
### The problem can be here ###
        url = '{}/{}/{}'.format(API_HOST, 'chat', 'Message')
        headers = {
            'Content-Type': 'application/json',
            'CB-Token': usertoken
        }
        request = HTTPRequest(
            url,
            method='POST',
            headers=headers,
            body=json.dumps(parameters).encode('utf-8')
        )
        response = await self.application.http_client.fetch(request)
        if response.code >= 200:
            self.set_status(response.code)
            data = json.loads(response.body.decode('utf-8'))
            messages = data.get('items')
            self.finish({
                'token': usertoken,
                'nr_results': len(messages),
                'results': messages
            })
        else:
            self.set_status(response.code)
            self.finish(json.loads(response.body.decode('utf-8')))

    def post(self):
        usertoken = self.get_body_argument('usertoken')
        receptor_id = self.get_body_argument('reciever', None)
        message = self.get_body_argument('message')
        data = self.get_body_argument('data', None)
        dialog_id = self.get_body_argument('dialog', None)
        if receptor_id is None:
            return self.send_message_to_chat(usertoken, receptor_id, message, data)
        elif dialog_id is None:
            return self.send_message_to_group(usertoken, dialog_id, message, data)
        else:
            self.set_status(400)
            self.finish({
                'errors': 'Needs a receptor or dialog id'
            })
```

Can you help me solve it? Thank you!

**Comment by AnnBenavides** [comment]
Forget it my bad
