### ISSUE TITLE
Push Notifications send via connectycube but not received

### ISSUE THREAD

**Issue by rexcode** [ConnectyCube/connectycube-reactnative-samples#275]
Hi,

I am able to successfully send a notification when initiating a  call but call receiver is not receiving the notification
notification is visible in the admin panel - as shown below

![image](https://user-images.githubusercontent.com/12795884/135860734-b4040669-7c82-48e4-8438-3f00ea3fa2f9.png)

have followed instructions given here - https://developers.connectycube.com/reactnative/push-notifications

Please guide

**Comment by DaveLomber** [comment]
@rexcode please let here know which platform you test (iOS / Android) and which RN you use - CLI or Expo

**Comment by rexcode** [comment]
My platform is Android

using RN CLI 
 "react-native": "0.63.2",
also using 
"react-native-onesignal": "^4.3.0",
 "react-native-push-notification": "^8.1.0",

**Comment by rexcode** [comment]
Hi there,

Please guide

**Comment by ccvlad** [comment]
Hi, @rexcode 

Could you show the log on the moment of sending the message and config which you're passing in `ConnectyCube.init(creds, config)`?

**Comment by rexcode** [comment]
Log - when sending chat - 

2021-10-14 14:54:18.376 1804-2285/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
2021-10-14 14:54:18.376 1804-2285/? E/GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
2021-10-14 14:54:19.495 1804-2285/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
2021-10-14 14:54:19.495 1804-2285/? E/GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
2021-10-14 14:54:20.171 12362-12675/com.pdmc.glmetaforiki I/ReactNativeJS: ----------sending Message-------------
2021-10-14 14:54:20.176 1837-1837/? W/adbd: timeout expired while flushing socket, closing
2021-10-14 14:54:20.195 1795-7129/? W/audio_hw_generic: Not supplying enough data to HAL, expected position 4962812 , only wrote 4962788
2021-10-14 14:54:20.415 1804-2285/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
2021-10-14 14:54:20.415 1804-2285/? E/GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8
2021-10-14 14:54:20.658 12362-12675/com.pdmc.glmetaforiki I/ReactNativeJS: '--------msg send success---------', '6167f74401d226054c000002'
2021-10-14 14:54:20.787 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
2021-10-14 14:54:20.787 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
2021-10-14 14:54:20.798 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
2021-10-14 14:54:20.799 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: getSelectedText on inactive InputConnection
2021-10-14 14:54:20.808 8307-8307/? I/GoogleInputMethodService: GoogleInputMethodService.onStartInput():2028 
2021-10-14 14:54:20.809 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
2021-10-14 14:54:20.809 8307-12897/? E/LstmTrainingCache: TrainingInputEventProcessor$1.onSuccess():441 onSuccess()
2021-10-14 14:54:20.809 8307-8307/? I/DeviceUnlockedTag: DeviceUnlockedTag.notifyDeviceLockStatusChanged():38 Notify device unlocked.
2021-10-14 14:54:20.810 8307-8307/? W/SessionManager: SessionManager.beginSession():55 Try to begin an already begun session [INPUT_SESSION], end it first
2021-10-14 14:54:20.810 8307-8307/? W/SessionManager: SessionManager.endSession():98 Child session [INPUT_VIEW_SESSION] is not ended while ending session [{TRAINING_CACHE_SESSION=1634203415177, IME_SESSION=1634203415177, INPUT_VIEW_SESSION=1634203415158, INPUT_SESSION=1634203415156}], ending it now.
2021-10-14 14:54:20.810 8307-8307/? W/SessionManager: SessionManager.endSession():98 Child session [IME_SESSION] is not ended while ending session [{TRAINING_CACHE_SESSION=1634203415177, IME_SESSION=1634203415177, INPUT_VIEW_SESSION=1634203415158, INPUT_SESSION=1634203415156}], ending it now.
2021-10-14 14:54:20.812 2028-2055/? E/memtrack: Couldn't load memtrack module
2021-10-14 14:54:20.812 2028-2055/? W/android.os.Debug: failed to get memory consumption info: -1
2021-10-14 14:54:20.815 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
2021-10-14 14:54:20.815 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
2021-10-14 14:54:20.815 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
2021-10-14 14:54:20.815 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
2021-10-14 14:54:20.816 2028-2055/? E/memtrack: Couldn't load memtrack module
2021-10-14 14:54:20.816 2028-2055/? W/android.os.Debug: failed to get memory consumption info: -1
2021-10-14 14:54:20.817 8307-8307/? I/GoogleInputMethodService: GoogleInputMethodService.onStartInputView():2175 
2021-10-14 14:54:20.818 8307-8307/? I/DeviceUnlockedTag: DeviceUnlockedTag.notifyDeviceLockStatusChanged():38 Notify device unlocked.
2021-10-14 14:54:20.824 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
2021-10-14 14:54:20.824 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
2021-10-14 14:54:20.825 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
2021-10-14 14:54:20.829 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: getSelectedText on inactive InputConnection
2021-10-14 14:54:20.831 8307-8307/? I/KeyboardViewUtil: KeyboardViewUtil.getKeyboardHeightRatio():170 systemKeyboardHeightRatio:1.000000; userKeyboardHeightRatio:1.000000.
2021-10-14 14:54:20.832 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
2021-10-14 14:54:20.832 8307-8307/? I/KeyboardWrapper: KeyboardWrapper.consumeEvent():288 Skip consuming an event as current keyboard is deactivated (state=0, keyboard existence=true)
2021-10-14 14:54:20.833 8307-8307/? I/VoiceInputManagerWrapper: VoiceInputManagerWrapper.shutdown():76 shutdown()
2021-10-14 14:54:20.833 8307-8307/? I/AndroidIME: AbstractIme.onDeactivate():207 LatinIme.onDeactivate()
2021-10-14 14:54:20.834 8307-8307/? W/SessionManager: SessionManager.endSession():90 Try to end a not begun session [IME_SESSION].
2021-10-14 14:54:20.835 8307-8307/? I/AndroidIME: AbstractIme.onActivate():86 LatinIme.onActivate() : EditorInfo = inputType=Text imeActionName=DONE dump=[inputType=0x24001 imeOptions=0x40000006 privateImeOptions=null actionLabel=null actionId=0 initialSelStart=4 initialSelEnd=4 initialCapsMode=0x0 hintText=Type a message... label=null packageName=com.pdmc.glmetaforiki fieldId=535 fieldName=null extras=null hintLocales=null contentMimeTypes=null ], IncognitoMode = false, DeviceLocked = false
2021-10-14 14:54:20.835 8307-8307/? I/Delight5Facilitator: Delight5Facilitator.initializeForIme():755 initializeForIme() : Locale = [en_US], layout = qwerty
2021-10-14 14:54:20.835 8307-8307/? I/VoiceInputManagerWrapper: VoiceInputManagerWrapper.cancelShutdown():54 cancelShutdown()
2021-10-14 14:54:20.835 8307-8307/? I/VoiceInputManagerWrapper: VoiceInputManagerWrapper.syncLanguagePacks():66 syncLanguagePacks()
2021-10-14 14:54:20.835 8307-8307/? I/LatinIme: LatinIme.updateEnableInlineSuggestionsOnDecoderSideFlags():1297 inline flag updated to:false
2021-10-14 14:54:20.836 8307-9428/? I/SpeechFactory: SpeechRecognitionFactory.maybeScheduleAutoPackDownloadForFallback():182 maybeScheduleAutoPackDownloadForFallback()
2021-10-14 14:54:20.837 8307-9428/? I/FallbackOnDeviceRecognitionProvider: FallbackOnDeviceRecognitionProvider.maybeScheduleAutoPackDownload():194 maybeScheduleAutoPackDownload() for language tag en-US
2021-10-14 14:54:20.844 8307-8307/? I/KeyboardWrapper: KeyboardWrapper.consumeEvent():288 Skip consuming an event as current keyboard is deactivated (state=0, keyboard existence=true)
2021-10-14 14:54:20.847 8307-8307/? I/KeyboardViewUtil: KeyboardViewUtil.calculateMaxKeyboardBodyHeight():62 leave 344 height for app when screen height:2028, header height:121 and isFullscreenMode:false, so the max keyboard body height is:1563
2021-10-14 14:54:20.847 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
2021-10-14 14:54:20.847 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
2021-10-14 14:54:20.847 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
2021-10-14 14:54:20.847 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
2021-10-14 14:54:20.850 8307-8307/? I/NormalModeController: NormalModeController.getKeyboardBodyViewHolderPaddingBottom():109 currentPrimeKeyboardType:SOFT systemPaddingBottom:-1
2021-10-14 14:54:20.851 8307-8745/? I/Delight5Decoder: Delight5DecoderWrapper.setKeyboardLayout():435 setKeyboardLayout()
2021-10-14 14:54:20.852 8307-8307/? I/KeyboardViewUtil: KeyboardViewUtil.calculateMaxKeyboardBodyHeight():62 leave 344 height for app when screen height:2028, header height:121 and isFullscreenMode:false, so the max keyboard body height is:1563
2021-10-14 14:54:20.854 8307-8307/? I/NormalModeController: NormalModeController.getKeyboardBodyViewHolderPaddingBottom():109 currentPrimeKeyboardType:SOFT systemPaddingBottom:-1
2021-10-14 14:54:20.854 8307-9447/? E/putmethod.lati: Invalid ID 0x00000217.
2021-10-14 14:54:20.854 8307-9447/? E/LstmTrainingCache: TrainingInputEventProcessor$SlotTask.process():120 Can't get resource name for input slot
    android.content.res.Resources$NotFoundException: Unable to find resource ID #0x217
        at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:276)
        at android.content.res.Resources.getResourceName(Resources.java:2064)
        at emb.a(PG:4)
        at elx.run(PG:3)
        at java.lang.Thread.run(Thread.java:919)
2021-10-14 14:54:20.859 8307-8307/? I/NormalModeController: NormalModeController.getKeyboardBodyViewHolderPaddingBottom():109 currentPrimeKeyboardType:SOFT systemPaddingBottom:-1
2021-10-14 14:54:20.866 8307-8307/? I/VoiceImeExtension: VoiceImeExtension.shouldStartVoiceInputAutomatically():354 No private IME option set to start voice input.
2021-10-14 14:54:20.869 8307-12586/? I/FederatedC2QExtension: FederatedC2QExtension.setupInferencing():557 Federated Conv2Query inferencing disabled, switching to baseline
2021-10-14 14:54:20.873 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
2021-10-14 14:54:20.873 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
2021-10-14 14:54:20.874 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
2021-10-14 14:54:20.876 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: getSelectedText on inactive InputConnection
2021-10-14 14:54:20.877 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
2021-10-14 14:54:20.879 8307-8307/? I/GoogleInputMethodService: GoogleInputMethodService.onStartInput():2028 
2021-10-14 14:54:20.880 8307-8307/? I/DeviceUnlockedTag: DeviceUnlockedTag.notifyDeviceLockStatusChanged():38 Notify device unlocked.
2021-10-14 14:54:20.880 8307-8307/? W/SessionManager: SessionManager.beginSession():55 Try to begin an already begun session [INPUT_SESSION], end it first
2021-10-14 14:54:20.880 8307-8307/? W/SessionManager: SessionManager.endSession():98 Child session [INPUT_VIEW_SESSION] is not ended while ending session [{TRAINING_CACHE_SESSION=1634203460835, IME_SESSION=1634203460834, INPUT_VIEW_SESSION=1634203460817, INPUT_SESSION=1634203460810}], ending it now.
2021-10-14 14:54:20.880 8307-8307/? W/SessionManager: SessionManager.endSession():98 Child session [IME_SESSION] is not ended while ending session [{TRAINING_CACHE_SESSION=1634203460835, IME_SESSION=1634203460834, INPUT_VIEW_SESSION=1634203460817, INPUT_SESSION=1634203460810}], ending it now.
2021-10-14 14:54:20.881 8349-8349/? D/BoundBrokerSvc: onBind: Intent { act=com.google.firebase.dynamiclinks.service.START pkg=com.google.android.gms }
2021-10-14 14:54:20.881 8349-8349/? D/BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.firebase.dynamiclinks.service.START pkg=com.google.android.gms }
2021-10-14 14:54:20.882 8307-8307/? I/GoogleInputMethodService: GoogleInputMethodService.onStartInputView():2175 
2021-10-14 14:54:20.883 8307-8307/? I/DeviceUnlockedTag: DeviceUnlockedTag.notifyDeviceLockStatusChanged():38 Notify device unlocked.
2021-10-14 14:54:20.883 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
2021-10-14 14:54:20.883 12362-12362/com.pdmc.glmetaforiki W/IInputConnectionWrapper: endBatchEdit on inactive InputConnection
2021-10-14 14:54:20.919 8307-8307/? I/KeyboardViewUtil: KeyboardViewUtil.getKeyboardHeightRatio():170 systemKeyboardHeightRatio:1.000000; userKeyboardHeightRatio:1.000000.
2021-10-14 14:54:20.926 8307-8307/? I/KeyboardWrapper: KeyboardWrapper.consumeEvent():288 Skip consuming an event as current keyboard is deactivated (state=0, keyboard existence=true)
2021-10-14 14:54:20.926 8307-8307/? I/VoiceInputManagerWrapper: VoiceInputManagerWrapper.shutdown():76 shutdown()
2021-10-14 14:54:20.927 8307-8307/? I/AndroidIME: AbstractIme.onDeactivate():207 LatinIme.onDeactivate()
2021-10-14 14:54:20.928 8307-8307/? W/SessionManager: SessionManager.endSession():90 Try to end a not begun session [IME_SESSION].
2021-10-14 14:54:20.928 8307-8307/? I/AndroidIME: AbstractIme.onActivate():86 LatinIme.onActivate() : EditorInfo = inputType=Text imeActionName=DONE dump=[inputType=0x24001 imeOptions=0x40000006 privateImeOptions=null actionLabel=null actionId=0 initialSelStart=0 initialSelEnd=0 initialCapsMode=0x2000 hintText=Type a message... label=null packageName=com.pdmc.glmetaforiki fieldId=535 fieldName=null extras=null hintLocales=null contentMimeTypes=null ], IncognitoMode = false, DeviceLocked = false
2021-10-14 14:54:20.929 8307-8307/? I/Delight5Facilitator: Delight5Facilitator.initializeForIme():755 initializeForIme() : Locale = [en_US], layout = qwerty
2021-10-14 14:54:20.929 8307-8307/? I/VoiceInputManagerWrapper: VoiceInputManagerWrapper.cancelShutdown():54 cancelShutdown()
2021-10-14 14:54:20.929 8307-8307/? I/VoiceInputManagerWrapper: VoiceInputManagerWrapper.syncLanguagePacks():66 syncLanguagePacks()
2021-10-14 14:54:20.930 8307-8307/? I/LatinIme: LatinIme.updateEnableInlineSuggestionsOnDecoderSideFlags():1297 inline flag updated to:false
2021-10-14 14:54:20.930 8307-9428/? I/SpeechFactory: SpeechRecognitionFactory.maybeScheduleAutoPackDownloadForFallback():182 maybeScheduleAutoPackDownloadForFallback()
2021-10-14 14:54:20.930 8307-9428/? I/FallbackOnDeviceRecognitionProvider: FallbackOnDeviceRecognitionProvider.maybeScheduleAutoPackDownload():194 maybeScheduleAutoPackDownload() for language tag en-US
2021-10-14 14:54:20.935 8307-8307/? I/KeyboardWrapper: KeyboardWrapper.consumeEvent():288 Skip consuming an event as current keyboard is deactivated (state=0, keyboard existence=true)
2021-10-14 14:54:20.939 8307-8307/? I/KeyboardViewUtil: KeyboardViewUtil.calculateMaxKeyboardBodyHeight():62 leave 344 height for app when screen height:2028, header height:121 and isFullscreenMode:false, so the max keyboard body height is:1563
2021-10-14 14:54:20.942 8307-8307/? I/NormalModeController: NormalModeController.getKeyboardBodyViewHolderPaddingBottom():109 currentPrimeKeyboardType:SOFT systemPaddingBottom:-1
2021-10-14 14:54:20.944 8307-8307/? I/KeyboardViewUtil: KeyboardViewUtil.calculateMaxKeyboardBodyHeight():62 leave 344 height for app when screen height:2028, header height:121 and isFullscreenMode:false, so the max keyboard body height is:1563
2021-10-14 14:54:20.948 8307-8307/? I/NormalModeController: NormalModeController.getKeyboardBodyViewHolderPaddingBottom():109 currentPrimeKeyboardType:SOFT systemPaddingBottom:-1
2021-10-14 14:54:20.949 8307-8745/? I/Delight5Decoder: Delight5DecoderWrapper.setKeyboardLayout():435 setKeyboardLayout()
2021-10-14 14:54:20.951 8307-8518/? I/NebulaeTrainingCacheMetricsProcessor: NebulaeTrainingCacheMetricsProcessor.processEndSession():242 No input action collection in this session, skip logging.
2021-10-14 14:54:20.954 8307-8307/? I/NormalModeController: NormalModeController.getKeyboardBodyViewHolderPaddingBottom():109 currentPrimeKeyboardType:SOFT systemPaddingBottom:-1
2021-10-14 14:54:20.965 8307-9447/? E/putmethod.lati: Invalid ID 0x00000217.
2021-10-14 14:54:20.965 8307-9447/? E/LstmTrainingCache: TrainingInputEventProcessor$SlotTask.process():120 Can't get resource name for input slot
    android.content.res.Resources$NotFoundException: Unable to find resource ID #0x217
        at android.content.res.ResourcesImpl.getResourceName(ResourcesImpl.java:276)
        at android.content.res.Resources.getResourceName(Resources.java:2064)
        at emb.a(PG:4)
        at elx.run(PG:3)
        at java.lang.Thread.run(Thread.java:919)
2021-10-14 14:54:20.971 8307-8307/? I/VoiceImeExtension: VoiceImeExtension.shouldStartVoiceInputAutomatically():354 No private IME option set to start voice input.
2021-10-14 14:54:20.976 8307-12587/? I/FederatedC2QExtension: FederatedC2QExtension.setupInferencing():557 Federated Conv2Query inferencing disabled, switching to baseline
2021-10-14 14:54:20.977 8307-8307/? W/InputContextProxy: InputContextProxy.applyClientDiffInternal():896 Ignore [FetchSuggestions] diff due to stale request: 221<227, inputStateId=209, lastInputStateId=214
2021-10-14 14:54:20.979 8307-8307/? W/InputContextProxy: InputContextProxy.applyClientDiffInternal():896 Ignore [FetchSuggestions] diff due to stale request: 223<227, inputStateId=211, lastInputStateId=214
2021-10-14 14:54:20.981 8307-8307/? W/InputContextProxy: InputContextProxy.applyClientDiffInternal():896 Ignore [FetchSuggestions] diff due to stale request: 225<227, inputStateId=213, lastInputStateId=214
2021-10-14 14:54:21.031 8307-8338/? I/putmethod.lati: Background young concurrent copying GC freed 126922(4884KB) AllocSpace objects, 10(520KB) LOS objects, 31% free, 11MB/16MB, paused 8.563ms total 46.790ms
2021-10-14 14:54:21.122 8349-8349/? D/BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
2021-10-14 14:54:21.122 8349-8349/? D/BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
2021-10-14 14:54:21.131 8349-8349/? D/BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
2021-10-14 14:54:21.137 8349-8349/? D/BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
2021-10-14 14:54:21.137 8349-8349/? D/BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
2021-10-14 14:54:21.142 8349-8349/? D/BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
2021-10-14 14:54:21.153 8349-8349/? D/BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
2021-10-14 14:54:21.153 8349-8349/? D/BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
2021-10-14 14:54:21.159 8349-8349/? D/BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
2021-10-14 14:54:21.172 8349-8349/? D/BoundBrokerSvc: onBind: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
2021-10-14 14:54:21.172 8349-8349/? D/BoundBrokerSvc: Loading bound service for intent: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
2021-10-14 14:54:21.186 8349-8349/? D/BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.common.BIND_SHARED_PREFS pkg=com.google.android.gms }
2021-10-14 14:54:21.416 1804-2285/? E/GnssHAL_GnssInterface: gnssSvStatusCb: a: input svInfo.flags is 8
2021-10-14 14:54:21.416 1804-2285/? E/GnssHAL_GnssInterface: gnssSvStatusCb: b: input svInfo.flags is 8


params passed in ConnectyCube.init(creds, config) - 
CC_CREDENTIALS -  {"appId": 5367, "authKey": "hDpyhJMzUtz5zY4", "authSecret": "BrHNW9EbuSn8X6k"}
CC_CONFIG -  {"debug": {"mode": 0}}

**Comment by ccvlad** [comment]
Make sure that you've set up push notification by the guide - https://developers.connectycube.com/reactnative/push-notifications?id=push-notifications

Configured the react-native-push-notification lib - https://github.com/zo0r/react-native-push-notification#installation

Also use real device to test push notification instead of Android emulator.

**Comment by rexcode** [comment]
Hi,
 I have followed the above instrucitons -

Now i am able to send notifciations from firebase and receive it in my app,
but still not able to receive notifications send via connectycube.

response from admin panel for push notification

![image](https://user-images.githubusercontent.com/12795884/137918784-b370bb49-0b11-4c79-8d82-3ecf6b89451a.png)

![image](https://user-images.githubusercontent.com/12795884/137918830-b128c22b-0453-483e-b8b4-4b76725e63b3.png)

Mismatch sender id error is gone but subscription error is still there,
I have checked the user details, the user is subscribed

![image](https://user-images.githubusercontent.com/12795884/137920297-5129d883-d182-4dc2-a5b8-6952c539b416.png)

**Comment by UmerQur3shi** [comment]
Hey @ccvlad, I'm having the same issue, notification is sent but I am not able to receive it and onNotification is not triggered.
Itried sending the notification from admin panel and still it says notification is sent but I'm not getting any notification on my device and emulator.
The logs from console are pasted below... 
[Response][11] [{"event": {"_id": "6187b0193d60060019811247", "active": true, "created_at": "2021-11-07T10:53:13Z", "date": null, "end_date": null, "environment": "development", "event_type": "one_shot", "id": 452464830, "kind": "API", "message": "eyJtZXNzYWdlIjoiQWxpY2UgaXMgY2FsbGluZyB5b3UiLCJpb3NfYmFkZ2UiOjF9", "name": null, "notification_channel": [Object], "period": null, "tag_query": null, "updated_at": "2021-11-07T10:53:13Z", "user_id": 5028617}}, {"event": {"_id": "6187b0193d60060019811248", "active": true, "created_at": "2021-11-07T10:53:13Z", "date": null, "end_date": null, "environment": "production", "event_type": "one_shot", "id": 251421350, "kind": "API", "message": "eyJtZXNzYWdlIjoiQWxpY2UgaXMgY2FsbGluZyB5b3UiLCJpb3NfYmFkZ2UiOjF9", "name": null, "notification_channel": [Object], "period": null, "tag_query": null, "updated_at": "2021-11-07T10:53:13Z", "user_id": 5028617}}]
 WARN  Notification sent.
Hoping to get a response soon, thanks.

**Comment by DaveLomber** [comment]
@rexcode are you using EXPO or RN CLI? 

Also, I checked the error from this https://github.com/ConnectyCube/connectycube-reactnative-samples/issues/275#issuecomment-946729264


Just to be clear, 
- when you send a push, it will create 2 events, one for production and another one for development 
- if a user has any subscription for specified env, then it will be delivered for this env 

2 more questions:
- which subscription env your user has?
- are both events have an error or only one?

**Comment by ccvlad** [comment]
Closed due to inactivity. Please create a new issue if needed.
